#!/usr/bin/python
import sys
import os
import smtplib, ssl

change_aut = os.environ['GERRIT_CHANGE_OWNER_EMAIL']
change_sub = os.environ['GERRIT_CHANGE_SUBJECT']
change_url = os.environ['GERRIT_CHANGE_URL']
build_number = os.environ['BUILD_NUMBER']
gerrit_change_number = os.environ['GERRIT_CHANGE_NUMBER']
gerrit_change_owner_name = os.environ['GERRIT_CHANGE_OWNER_NAME']

print(change_url)

# split and add 'http' for email restriction
split_http = change_url.split('http')
change_url = 'http' + split_http[1]

#from env variable : ToDo: use link directly

change_url = 'http'+'://bltsp02974.lnties.com:8085/c/MIL_UT_Tenneco/+/'+ gerrit_change_number +'/'
print(change_url)

build_url = 'http'+'://bltsp02974.lnties.com:8080/job/Tenneco_pipelinejob/' + build_number + '/execution/node/3/ws/'

#extracting reviewer name
split_review_name = change_sub.split(':')
get_review_name = split_review_name[1]
get_review_name = get_review_name.strip()

review_comments = split_review_name[0].split('review')
print(get_review_name)

#author email id
author_email = change_aut

# smtp data
smtp_server = 'smtp.gmail.com'
port = 587
local_hostname = 'localhost'
context = ssl.create_default_context()
sender_email = 'jenkinstrigger2020@gmail.com'
password = 'Target@2020'

# reviewer email id's
ps_number_pair = {'murugan': 'murugan.c@ltts.com',
                  'madhu': 'madhukumar.tm@ltts.com',
                  'sampath': 'sampath.kumar@Ltts.com',
                  'kiran': 'Kiran.Kulkarni@Ltts.com',
                  'aniket': 'Aniket.DeepakBhoite@Ltts.com',
                  'prashanth': 'Prashanth.KS@Ltts.com',
                  'rashmi': 'Rashmi.P@Ltts.com',
                  'amit': 'Amit.Pandey@Ltts.com',
                  'prasanna': 'Prasanna.KB@Ltts.com'}

#extracting reviewer email id 
key_list = list(ps_number_pair.keys()) 
val_list = list(ps_number_pair.values()) 
review_email = val_list[key_list.index(get_review_name)]

# email body
message = """
Subject: Jenkins Build Trigger

This is AutoGenerated Mail. Please do not reply.
""" +'\n'+ 'Author: '+ gerrit_change_owner_name +' has commited a checkin with review subject : ' + review_comments[0] +'\n'+ """Build is Success. 

Please find Build Workspace : """ + build_url + '\n' + '\n' +  '\n' + '\n'+ 'Contact Jenkins admin if any query: madhukumar.tm@ltts.com' '\n'

toAddr = [author_email, review_email]

# sending email 
with smtplib.SMTP(smtp_server, port) as server:
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login(sender_email, password)
    server.sendmail(sender_email, toAddr, message)
    server.quit()


#EOF